version: "3.9"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: roots
    volumes:
      - ./dbs/mysql:/home/dev
    ports:
      - "3306:3306"
